/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stm32f4xx.h>

void GPIO_init();
void Timer2_init();
void Tim2_delay();
int main(void)
{
	GPIO_init();
	Timer2_init();
	while(1){
		GPIOA-ODR |=(1<<5);
		Tim2_delay();
		GPIOA-ODR &=~(1<<5);
		Tim2_delay();
	}

}

void GPIO_init(){
	RCC->AHB1ENR |= (1<<0);
	RCC->APB1ENR |= (1<<0);
	GPIOA->MODER &=~(1<<11);
	GPIOA->MODER |=(1<<10);


}

void Timer2_init(){
	TIM2->PSC=16000;
	TIM2->ARR=1000-1;
	TIM2->CNT=0;
	TIM2->CR1 |=(1<<0);

}
void Tim2_delay(){
	while(!(TIM2->SR &(1<<0)));
	TIM2->SR &= ~(1<<0);
}
