/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
void gpio_init();

uint32_t *ABh1_RCC=(uint32_t*)0x40023830;
uint32_t *GPIOA_Moder=(uint32_t*)0x40020000;
uint32_t *GPIOA_ODR=(uint32_t*)0x40020014;
uint32_t *GPIOC_ODR_LED=(uint32_t*)0x40020814;
uint32_t *GPIOC_MODER_LED6=(uint32_t*)0x40020800;

int main(void)
{
	gpio_init();
while(1){
		int n=0;

				if(n==0){
					*GPIOC_ODR_LED &= ~(1 << 6);
					*GPIOA_ODR &=~(1<<5);
					delay();
					n++;

				}
				if(n==1){
							*GPIOC_ODR_LED |= (1 << 6);
							*GPIOA_ODR &=~(1<<5);
							delay();
							n++;

						}
				if(n==2){
									*GPIOC_ODR_LED &= ~(1 << 6);
									*GPIOA_ODR |= (1 << 5);
									delay();
									n++;

								}
				if(n==3){
											*GPIOC_ODR_LED |= (1 << 6);
											*GPIOA_ODR |= (1 << 5);
											delay();
											n=0;

										}

			}

}



void delay(){
	for(int i=0;i<5000000;i++){

	}
}
void gpio_init(){
	*ABh1_RCC |= (1<<0);
	*ABh1_RCC |= (1<<2);

	*GPIOA_Moder &=(~(1<<11));
	    *GPIOA_Moder|=(1<<10);

	    *GPIOC_MODER_LED6 &=(~(1<<13));
	    *GPIOC_MODER_LED6 |=(1<<12);

	}
